/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visao;

import javax.swing.JOptionPane;

/**
 *
 * @author tayara.5970
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton6 = new javax.swing.JButton();
        jMenu1 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        btmcadastrar = new javax.swing.JButton();
        btmalterar = new javax.swing.JButton();
        btmremover = new javax.swing.JButton();
        btmlistar = new javax.swing.JButton();
        btmvender = new javax.swing.JButton();

        jButton6.setText("jButton6");

        jMenu1.setText("jMenu1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btmcadastrar.setText("CADASTRAR");
        btmcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmcadastrarActionPerformed(evt);
            }
        });

        btmalterar.setText("ALTERAR");

        btmremover.setText("REMOVER");
        btmremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmremoverActionPerformed(evt);
            }
        });

        btmlistar.setText("LISTAR");

        btmvender.setText("VENDER");
        btmvender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmvenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btmcadastrar)
                .addGap(18, 18, 18)
                .addComponent(btmalterar)
                .addGap(18, 18, 18)
                .addComponent(btmremover)
                .addGap(18, 18, 18)
                .addComponent(btmlistar)
                .addGap(18, 18, 18)
                .addComponent(btmvender)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmcadastrar)
                    .addComponent(btmalterar)
                    .addComponent(btmremover)
                    .addComponent(btmlistar)
                    .addComponent(btmvender))
                .addContainerGap(453, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmcadastrarActionPerformed
    MenuEscolhaCategoria menuEscolhaCategoria = new MenuEscolhaCategoria();
    
    menuEscolhaCategoria.setLocationRelativeTo(null);
    menuEscolhaCategoria.setVisible(true);
    
    
    }//GEN-LAST:event_btmcadastrarActionPerformed

    private void btmremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmremoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmremoverActionPerformed

    private void btmvenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmvenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmvenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmalterar;
    private javax.swing.JButton btmcadastrar;
    private javax.swing.JButton btmlistar;
    private javax.swing.JButton btmremover;
    private javax.swing.JButton btmvender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
